name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        # Create the `gh-pages` branch if it doesn't exist
        git checkout -B gh-pages

        # Replace 'your-username' with your GitHub username
        git add -f index.html styles.css
        git commit -m "Deploy to GitHub Pages"
        git push -f origin gh-pages
